FROM node:22-alpine

RUN apk update && apk upgrade && apk add --no-cache git libc6-compat

WORKDIR /app

RUN mkdir ~/.npm-global && npm config set cache ~/.npm-global

# Copy only the files needed for migrations
COPY ../package.json ./
# COPY ../tsconfig.json ./
COPY ../src/migrations/ ./migrations/
COPY ../dataSource.ts ./
# COPY ../src/entities ./

RUN npm install

CMD ["npx", "typeorm-ts-node-commonjs", "migration:run", "--dataSource", "dataSource.ts"]